from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func



class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    broker_number = db.Column(db.String(50))
    group_identifier =  db.Column(db.String(50))

    def is_broker(self):
        return self.broker_number.startswith('B0')
    
    def is_admin(self):
        return self.broker_number == 'admin'
    
    def is_mwm(self):
        return self.broker_number == 'mcalvanywealth'
    
    

class InboundPerformanceData(db.Model):
    performance_id_in = db.Column(db.Integer, primary_key=True)
    direction = db.Column(db.String(50))
    duration = db.Column(db.Integer)
    from_number = db.Column(db.String(50))
    ring_duration = db.Column(db.Integer)
    start_date = db.Column(db.DateTime)
    to_number = db.Column(db.String(50))
    answered = db.Column(db.Boolean)
    user_id_in = db.Column(db.String(100))
    name_in = db.Column(db.String(100))

class OutboundPerformanceData(db.Model):
    performance_id_out = db.Column(db.Integer, primary_key=True)
    direction = db.Column(db.String(50))
    duration = db.Column(db.Integer)
    from_number = db.Column(db.String(50))
    ring_duration = db.Column(db.Integer)
    start_date = db.Column(db.DateTime)
    to_number = db.Column(db.String(50))
    answered = db.Column(db.Boolean)
    name_out = db.Column(db.String(100))
    user_id_out = db.Column(db.String(100))

class TradesTable(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    TRADE_NUM = db.Column(db.String(255))
    TD = db.Column(db.DateTime)
    TRADE_TYPE = db.Column(db.String(255))
    CLIENT_NUM = db.Column(db.String(255))
    TRADE_BROKER = db.Column(db.String(255))
    TRADER = db.Column(db.String(255))
    ITEM_CODE = db.Column(db.String(255))
    QUANTITY = db.Column(db.Integer)
    EXTENDED = db.Column(db.Float)

class LeadsTable(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    LeadNumbers = db.Column(db.String(50))
    BrokerName = db.Column(db.String(50))
    BrokerNum = db.Column(db.String(50), nullable=True)
    LeadSource = db.Column(db.String(50), nullable=True)
    Createdate = db.Column(db.DateTime)

class ClientsTable(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    LeadNumbers = db.Column(db.String(50))
    BrokerName = db.Column(db.String(50))
    BrokerNum = db.Column(db.String(50), nullable=True)
    LeadSource = db.Column(db.String(50), nullable=True)
    Createdate = db.Column(db.DateTime)

class Updated_Portfolio(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    TRADE_NUM = db.Column(db.String(50))
    TD = db.Column(db.DateTime)
    TRADE_TYPE = db.Column(db.String(50))
    CLIENT_NUM = db.Column(db.String(50))
    TRADE_BROKER = db.Column(db.String(50))
    TRADER = db.Column(db.String(50))
    ITEM_CODE = db.Column(db.String(50))
    QUANTITY = db.Column(db.Integer)
    EXTENDED = db.Column(db.Float)
    UNIT_PRICE = db.Column(db.Float)

class HistoricalCoinPriceBid(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    TD = db.Column(db.DateTime, nullable=False)
    Gold_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_oz = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_2_oz = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_4_oz = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_10_oz = db.Column(db.Float, nullable=True)
    Gold_American_Buffalo_1_oz = db.Column(db.Float, nullable=True)
    Gold_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Gold_Canadian_Maple_Leaf_1_10_oz = db.Column(db.Float, nullable=True)
    Gold_South_African_Krugerrand_1_oz = db.Column(db.Float, nullable=True)
    Gold_Australian_Kangaroo_1_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Philharmonic_1_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Philharmonic_1_4_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Philharmonic_1_10_oz = db.Column(db.Float, nullable=True)
    Gold_Mexican_Fifty_Peso_1_2_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Corona_9802_oz = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_1oz = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_10oz = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_1_kg = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_100_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_10_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_1_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_100_oz = db.Column(db.Float, nullable=True)
    Silver_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Silver_American_Eagle_Coin_1_oz = db.Column(db.Float, nullable=True)
    Silver_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Round_1_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_1000_oz = db.Column(db.Float, nullable=True)
    US_40_Silver_Coinage_295_oz = db.Column(db.Float, nullable=True)
    US_90_Silver_Coinage_715_oz = db.Column(db.Float, nullable=True)
    Platinum_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Platinum_American_Eagle_1_oz = db.Column(db.Float, nullable=True)
    Platinum_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Platinum_Bullion_Bar_1_oz = db.Column(db.Float, nullable=True)
    Platinum_Bullion_Bar_10_oz = db.Column(db.Float, nullable=True)
    Platinum_Bullion_Bars_50_oz = db.Column(db.Float, nullable=True)
    Palladium_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Palladium_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Palladium_Bullion_Bars_1_oz = db.Column(db.Float, nullable=True)
    Palladium_Bullion_Bars_10_oz = db.Column(db.Float, nullable=True)
    Palladium_Bullion_Bars_100_oz = db.Column(db.Float, nullable=True)


class HistoricalCoinPriceAsk(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    TD = db.Column(db.DateTime, nullable=False)
    Gold_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_oz = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_2_oz = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_4_oz = db.Column(db.Float, nullable=True)
    Gold_American_Eagle_1_10_oz = db.Column(db.Float, nullable=True)
    Gold_American_Buffalo_1_oz = db.Column(db.Float, nullable=True)
    Gold_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Gold_Canadian_Maple_Leaf_1_10_oz = db.Column(db.Float, nullable=True)
    Gold_South_African_Krugerrand_1_oz = db.Column(db.Float, nullable=True)
    Gold_Australian_Kangaroo_1_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Philharmonic_1_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Philharmonic_1_4_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Philharmonic_1_10_oz = db.Column(db.Float, nullable=True)
    Gold_Mexican_Fifty_Peso_1_2_oz = db.Column(db.Float, nullable=True)
    Gold_Austrian_Corona_9802_oz = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_1oz = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_10oz = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_1_kg = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_100_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_10_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_1_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_100_oz = db.Column(db.Float, nullable=True)
    Silver_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Silver_American_Eagle_Coin_1_oz = db.Column(db.Float, nullable=True)
    Silver_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Round_1_oz = db.Column(db.Float, nullable=True)
    Silver_Bullion_Bar_1000_oz = db.Column(db.Float, nullable=True)
    US_40_Silver_Coinage_295_oz = db.Column(db.Float, nullable=True)
    US_90_Silver_Coinage_715_oz = db.Column(db.Float, nullable=True)
    Platinum_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Platinum_American_Eagle_1_oz = db.Column(db.Float, nullable=True)
    Platinum_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Platinum_Bullion_Bar_1_oz = db.Column(db.Float, nullable=True)
    Platinum_Bullion_Bar_10_oz = db.Column(db.Float, nullable=True)
    Platinum_Bullion_Bars_50_oz = db.Column(db.Float, nullable=True)
    Palladium_Bulk_Generic_Bullion = db.Column(db.Float, nullable=True)
    Palladium_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=True)
    Palladium_Bullion_Bars_1_oz = db.Column(db.Float, nullable=True)
    Palladium_Bullion_Bars_10_oz = db.Column(db.Float, nullable=True)
    Palladium_Bullion_Bars_100_oz = db.Column(db.Float, nullable=True)

class CurrentCoinRatios(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_index = db.Column(db.String(150), nullable=False)
    Gold_Bulk_Generic_Bullion = db.Column(db.Float, nullable=False)
    Gold_American_Eagle_1_oz = db.Column(db.Float, nullable=False)
    Gold_American_Eagle_1_2_oz = db.Column(db.Float, nullable=False)
    Gold_American_Eagle_1_4_oz = db.Column(db.Float, nullable=False)
    Gold_American_Eagle_1_10_oz = db.Column(db.Float, nullable=False)
    Gold_American_Buffalo_1_oz = db.Column(db.Float, nullable=False)
    Gold_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=False)
    Gold_Canadian_Maple_Leaf_1_10_oz = db.Column(db.Float, nullable=False)
    Gold_South_African_Krugerrand_1_oz = db.Column(db.Float, nullable=False)
    Gold_Australian_Kangaroo_1_oz = db.Column(db.Float, nullable=False)
    Gold_Austrian_Philharmonic_1_oz = db.Column(db.Float, nullable=False)
    Gold_Austrian_Philharmonic_1_4_oz = db.Column(db.Float, nullable=False)
    Gold_Austrian_Philharmonic_1_10_oz = db.Column(db.Float, nullable=False)
    Gold_Mexican_Fifty_Peso_1_2_oz = db.Column(db.Float, nullable=False)
    Gold_Austrian_Corona_9802_oz = db.Column(db.Float, nullable=True)
    Gold_Bullion_Bar_1oz = db.Column(db.Float, nullable=False)
    Gold_Bullion_Bar_10oz = db.Column(db.Float, nullable=False)
    Gold_Bullion_Bar_1_kg = db.Column(db.Float, nullable=False)
    Gold_Bullion_Bar_100_oz = db.Column(db.Float, nullable=False)
    Silver_Bullion_Bar_10_oz = db.Column(db.Float, nullable=False)
    Silver_Bullion_Bar_1_oz = db.Column(db.Float, nullable=False)
    Silver_Bullion_Bar_100_oz = db.Column(db.Float, nullable=False)
    Silver_Bulk_Generic_Bullion = db.Column(db.Float, nullable=False)
    Silver_American_Eagle_Coin_1_oz = db.Column(db.Float, nullable=False)
    Silver_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=False)
    Silver_Bullion_Round_1_oz = db.Column(db.Float, nullable=False)
    Silver_Bullion_Bar_1000_oz = db.Column(db.Float, nullable=False)
    US_40_Silver_Coinage_295_oz = db.Column(db.Float, nullable=False)
    US_90_Silver_Coinage_715_oz = db.Column(db.Float, nullable=False)
    Platinum_Bulk_Generic_Bullion = db.Column(db.Float, nullable=False)
    Platinum_American_Eagle_1_oz = db.Column(db.Float, nullable=False)
    Platinum_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=False)
    Platinum_Bullion_Bar_1_oz = db.Column(db.Float, nullable=False)
    Platinum_Bullion_Bar_10_oz = db.Column(db.Float, nullable=False)
    Platinum_Bullion_Bars_50_oz = db.Column(db.Float, nullable=False)
    Palladium_Bulk_Generic_Bullion = db.Column(db.Float, nullable=False)
    Palladium_Canadian_Maple_Leaf_1_oz = db.Column(db.Float, nullable=False)
    Palladium_Bullion_Bars_1_oz = db.Column(db.Float, nullable=False)
    Palladium_Bullion_Bars_10_oz = db.Column(db.Float, nullable=False)
    Palladium_Bullion_Bars_100_oz = db.Column(db.Float, nullable=False)

class ToggleState(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    feature_name = db.Column(db.String(100), unique=True, nullable=False)
    is_enabled = db.Column(db.Boolean, default=True, nullable=False)


class RatioTradesTable(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    TD = db.Column(db.DateTime)
    TRADE_NUM = db.Column(db.String(255))
    TRADE_TYPE = db.Column(db.String(255))
    CLIENT_NUM = db.Column(db.String(255))
    TRADE_BROKER = db.Column(db.String(255))
    TRADER = db.Column(db.String(255))
    ITEM_CODE = db.Column(db.String(255))
    QUANTITY = db.Column(db.Float)
    EXTENDED = db.Column(db.Float)
    UNIT_PRICE = db.Column(db.Float)
    Gold_Bulk_Generic_Bullion = db.Column(db.Float)
    Gold_American_Eagle_1_oz = db.Column(db.Float)
    Gold_American_Eagle_1_2_oz = db.Column(db.Float)
    Gold_American_Eagle_1_4_oz = db.Column(db.Float)
    Gold_American_Eagle_1_10_oz = db.Column(db.Float)
    Gold_American_Buffalo_1_oz = db.Column(db.Float)
    Gold_Canadian_Maple_Leaf_1_oz = db.Column(db.Float)
    Gold_Canadian_Maple_Leaf_1_10_oz = db.Column(db.Float)
    Gold_South_African_Krugerrand_1_oz = db.Column(db.Float)
    Gold_Australian_Kangaroo_1_oz = db.Column(db.Float)
    Gold_Austrian_Philharmonic_1_oz = db.Column(db.Float)
    Gold_Austrian_Philharmonic_1_4_oz = db.Column(db.Float)
    Gold_Austrian_Philharmonic_1_10_oz = db.Column(db.Float)
    Gold_Mexican_Fifty_Peso_1_2_oz = db.Column(db.Float)
    Gold_Austrian_Corona_9802_oz = db.Column(db.Float)
    Gold_Bullion_Bar_1oz = db.Column(db.Float)
    Gold_Bullion_Bar_10oz = db.Column(db.Float)
    Gold_Bullion_Bar_1_kg = db.Column(db.Float)
    Gold_Bullion_Bar_100_oz = db.Column(db.Float)
    Silver_Bullion_Bar_10_oz = db.Column(db.Float)
    Silver_Bullion_Bar_1_oz = db.Column(db.Float)
    Silver_Bullion_Bar_100_oz = db.Column(db.Float)
    Silver_Bulk_Generic_Bullion = db.Column(db.Float)
    Silver_American_Eagle_Coin_1_oz = db.Column(db.Float)
    Silver_Canadian_Maple_Leaf_1_oz = db.Column(db.Float)